<?php


namespace Buqiu\Repository\Tests;

use Mockery as m;
use PHPUnit\Framework\TestCase;

class RepositoryTest extends TestCase
{
    /**
     * @var
     */
    protected $mock;

    /**
     * @var
     */
    protected $repository;

    /**
     * Change the autogenerated stub
     */
    public function setUp(): void
    {
        $this->mock = m::mock('Illuminate\Database\Eloquent\Model');
    }

    /**
     * 测试仓库
     */
    public function testRepository()
    {
        $this->assertTrue(true);
    }
}
